# Generated by Django 3.2 on 2021-06-09 10:12
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'network/fixtures/User.json')
    call_command('loaddata', 'network/fixtures/Post.json')

class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
